merge feat/challenge_03_loops-conditionals to merge
Daniel94y1/JavaScript-foundations-challenge-1 pull request #4
Opened 2023-11-02 02:10 UTC by Daniel94y1

2023-11-05 17:24 UTC, tictools commented on challenge_03_loops-conditionals/index.js
⚠️ FIX:remove file

2023-11-05 17:29 UTC, tictools requested changes

2023-11-05 17:29 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_00.js
> +if (animal === "cat") {
⚠️ FIX: Change animal to different values to make sure it works in all cases

2023-11-05 17:29 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
> +if (number % 2 === 0) {
⚠️ FIX: Change animal to different values to make sure it works in all cases

2023-11-05 17:29 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +console.log("Even numbers between 10 and 40:");
You should take in account what `i` variable is storing. Is this variable referring to any index in this case?

⚠️ FIX: rename properly `i` variable

2023-11-05 17:29 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +for (let i = 1; i <= 100; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case?

⚠️ FIX: rename properly `i` variable

2023-11-05 17:29 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_01.js
> +while (evenNumber <= 40) {
These loops should iterate over all numbers in between 10 and 40, printing only the odd/even ones, depending on its own logic.

⚠️ FIX: iterate over all numbers and print only the odd/even ones

2023-11-05 17:29 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_02.js
> +let counter = 1;
This is the output of your script...
```
Checkpoint! 10
Checkpoint! 20
Checkpoint! 30
Checkpoint! 40
Checkpoint! 50
Half way there!
Checkpoint! 60
Checkpoint! 70
Checkpoint! 80
Checkpoint! 90
Checkpoint! 100
You made it!
All, done!
```

...have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-06 15:38 UTC, Daniel94y1 commented
complete revision

2023-11-11 12:14 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +  console.log(`Even numbers between ${start} and ${end}:`);
🚀

2023-11-11 12:18 UTC, tictools requested changes

2023-11-11 12:18 UTC, tictools commented on challenge_03_loops-conditionals/README.md
FIX: more file at root level. out of challenge_03 folder.

![image](https://github.com/Daniel94y1/JavaScript-foundations-challenge-1/assets/25468240/a9bf90a4-546e-4dd7-85ba-a50e73eb6d4b)

2023-11-11 20:10 UTC, tictools approved these changes

2023-11-13 17:30 UTC, nuriaruiz97 approved these changes

2023-11-13 17:30 UTC, nuriaruiz97 commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_00.js
I think you can improve your code by simplifying the animalChecker function and eliminating redundant checks.

2023-11-13 17:30 UTC, nuriaruiz97 commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
nice!

2023-11-13 17:30 UTC, nuriaruiz97 commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_02.js
the problem in this exercise isn't in the logic conditions they give you, it's in the order of the conditions!

2023-11-13 17:30 UTC, nuriaruiz97 commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
nice!!

2023-11-13 17:30 UTC, nuriaruiz97 commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_01.js
check the  brackets

2023-11-13 17:30 UTC, nuriaruiz97 commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
check the brackets

2023-11-13 17:30 UTC, nuriaruiz97 commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_00.js
check the brackets

2023-11-13 17:30 UTC, nuriaruiz97 commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_01.js
Check the barckets, ensure consistent conditions for even and odd numbers in loops, and move the console.log statement outside the second while loop

2023-11-13 17:35 UTC, merged